services:
  - type: web
    name: controle-empresas-web
    runtime: static
    branch: main
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_SUPABASE_URL
        value: https://qnqmmrvhqxpenhqyesbc.supabase.co
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
